name: Newman run 

on: 
  push: 
    branches:
      - main

jobs: 
  newman:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Create dir for report
        run: 
          mkdir testArtifacts

      - name: install Newman
        run: 
          sudo npm i -g  newman
          sudo npm i -g  newman-reporter-htmlextra

      - name: Run Test
        run: newman run ServeRest.postman_collection.json -e seveRest_env.postman_environment.json -r cli -r htmlextra

      - name: Report
        uses: actions/upload-artifact@v4
        with: 
          name: Report
          path: newman


          
